# Generated by Django 4.0.4 on 2022-05-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Super',
            new_name='Song',
        ),
    ]
